### PR TITLE
Add support for Software Licensing license checks, and restructure #1 issue/1

### PR DESCRIPTION
**Pull request by cklosowski**
#1

### CODE REVIEW

**Comment by grappler** [comment]
I don't think we should be using `extract`

**Comment by cklosowski** [comment]
@grappler I'm just matching the current standard of the plugin. I'll open a new issue to fully vet the removal of `extract` for it all.

**Comment by grappler** [comment]
Ok, It feels like the class is being used as a poor man's namespace.

**Comment by cklosowski** [comment]
@grappler It's simply used as a way to make it more accessible to things extending.

By making it part of the main instance of the primary class, it allows us to access it from:
`edd_additional_shortcodes()->integrations['software_licensing']`

**Comment by cklosowski** [comment]
We follow this same pattern in EDD Core and software licensing as well since we load the main plugin class as a singleton.

**Comment by grappler** [comment]
Ok, if that is how it's done in EDD. 😄

**Comment by cklosowski** [comment]
It is..for now.

**Pull request merged**
